# Project: dk2mtool
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = dk2mtool.o lbfileio.o dk2mfile.o
LINKOBJ  = dk2mtool.o lbfileio.o dk2mfile.o
LIBS     = -L"A:/Downloads/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/lib" -L"A:/Downloads/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"A:/Downloads/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/include" -I"A:/Downloads/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/x86_64-w64-mingw32/include" -I"A:/Downloads/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"A:/Downloads/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/include" -I"A:/Downloads/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/x86_64-w64-mingw32/include" -I"A:/Downloads/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"A:/Downloads/Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = dk2mtool.exe
CXXFLAGS = $(CXXINCS) -Wfatal-errors -mwindows
CFLAGS   = $(INCS) -Wfatal-errors -mwindows
DEL      = A:\Downloads\Embarcadero_Dev-Cpp_6.3_TDM-GCC_9.2_Portable\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

dk2mtool.o: dk2mtool.c
	$(CC) -c dk2mtool.c -o dk2mtool.o $(CFLAGS)

lbfileio.o: lbfileio.c
	$(CC) -c lbfileio.c -o lbfileio.o $(CFLAGS)

dk2mfile.o: dk2mfile.c
	$(CC) -c dk2mfile.c -o dk2mfile.o $(CFLAGS)
